name: CI

on:
  push:
    branches:
    - preview

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy Preview
      run: |
        git config --global user.email "kevin@austincodingacademy.com"
        git config --global user.name "Kevin Colten"
        echo preview.circleeducation.com >> CNAME"
        npx gh-pages --repo git@github.com:CircleCodeHouse/preview.circleeducation.com.git -d . -t
